kind: Pod
apiVersion: v1
metadata: 
  name: env-test
  labels:
    course: k8
    trainer: sivakumar
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
     value: 'kubernates'
    - name: duration
      value: '120hrs'
   