apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port

#if your mentioning only service and attaching the service to pod then
 this is called cluster ip, here pods are communicating only inside cluser through cluser ip